/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import Quest22Image from 'src/assets/images/Roadmap_Quest2_2.png';
import { styled } from '@mui/material/styles';
import Navbar2 from 'src/components/Navbar2/Navbar2';

const Roadmap1 = styled('div')({
  backgroundColor: `rgba(208, 36, 191, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const WwwQuestAi = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(85, 85, 85, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
  position: `absolute`,
  left: `61px`,
  top: `1963px`,
}));

const FigmaToReactUpgradeY = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(85, 85, 85, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `61px`,
  top: `1907px`,
}));

const Quest22 = styled('img')({
  height: `46.47px`,
  width: `189.22px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `59px`,
  top: `1839px`,
});

const Hrucoin = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `80px`,
  letterSpacing: `-2.4px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `513px`,
  position: `absolute`,
  left: `518px`,
  top: `257px`,
});

const Roadmap2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `45px`,
  letterSpacing: `-1.35px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `513px`,
  position: `absolute`,
  left: `596px`,
  top: `331px`,
});

const Label = styled('div')({
  background: `linear-gradient(90deg, rgba(123, 97, 255, 1) 27.623125519423546%, rgba(254, 136, 136, 1) 89.6145617438896%)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25), 0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `50px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `20px`,
  boxSizing: `border-box`,
  width: `457px`,
  height: `48px`,
  left: `468px`,
  top: `398px`,
});

const Frame1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px 5px`,
  boxSizing: `border-box`,
  height: `24px`,
  margin: `0px`,
});

const Text = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `3px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Label1 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `29px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

const Navbar21 = styled(Navbar2)(({ theme }) => ({
  width: `1440px`,
  height: `57px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Hrucoin1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `-0.66px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `513px`,
  position: `absolute`,
  left: `134px`,
  top: `19px`,
});

function Roadmap(props) {
  return (
    <Roadmap1>
      <Helmet>
        <title>Roadmap</title>
      </Helmet>
      <WwwQuestAi>{`www.quest.ai`}</WwwQuestAi>
      <FigmaToReactUpgradeY>
        {`Figma to React. Upgrade your workflow.`}
      </FigmaToReactUpgradeY>
      <Quest22 src={Quest22Image} loading="lazy" alt={'Quest2 2'} />
      <Hrucoin>{`HRUCOIN`}</Hrucoin>
      <Roadmap2>{`Roadmap.`}</Roadmap2>
      <Label>
        <Frame1>
          <Text>
            <Label1>{`Coming Soon.`}</Label1>
          </Text>
        </Frame1>
      </Label>
      <Navbar21 />
      <Hrucoin1>{`HRUCOIN`}</Hrucoin1>
    </Roadmap1>
  );
}

export default Roadmap;
