/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import { styled } from '@mui/material/styles';
import Navbar2 from 'src/components/Navbar2/Navbar2';

const Presale1 = styled('div')({
  backgroundColor: `rgba(208, 36, 191, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: '100%',
  width: '100%',
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Navbar21 = styled(Navbar2)(({ theme }) => ({
  zIndex: `3`,
}));

const Hrucoin = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `128px`,
  letterSpacing: `-3.84px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `568px`,
  zIndex: `2`,
});

const Presale2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `128px`,
  letterSpacing: `-3.84px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `568px`,
  zIndex: `1`,
});

const Label = styled('div')({
  background: `linear-gradient(90deg, rgba(123, 97, 255, 1) 27.623125519423347%, rgba(254, 136, 136, 1) 89.61456174388938%)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25), 0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `50px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `20px`,
  boxSizing: `border-box`,
  height: `46px`,
  width: `461px`,
  zIndex: `0`,
});

const Frame1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px 5px`,
  boxSizing: `border-box`,
  height: `24px`,
  margin: `0px`,
});

const Text = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `3px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Label1 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `29px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

function Presale(props) {
  return (
    <Presale1>
      <Helmet>
        <title>Presale</title>
      </Helmet>
      <Navbar21 />
      <Hrucoin>{`HRUCOIN`}</Hrucoin>
      <Presale2>{`Presale`}</Presale2>
      <Label>
        <Frame1>
          <Text>
            <Label1>{`Not Yet Open.`}</Label1>
          </Text>
        </Frame1>
      </Label>
    </Presale1>
  );
}

export default Presale;
