/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ImgIconImage from 'src/assets/images/sidebaricon_img_icon.png';
import { styled } from '@mui/material/styles';

const Property1Dashboard = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: '100%',
});

const Icon1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `32px`,
  height: `32px`,
  margin: `0px`,
});

const ImgIcon = styled('img')({
  height: `19.66px`,
  width: `17.69px`,
  margin: `0px`,
});

function SidebarIcon(props) {
  return (
    <Property1Dashboard>
      <Icon1>
        <ImgIcon src={ImgIconImage} loading="lazy" alt={'img:icon'} />
      </Icon1>
    </Property1Dashboard>
  );
}

export default SidebarIcon;
