/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { SvgIcon } from '@mui/material';
import { ReactComponent as DateRangeFilled1 } from 'src/assets/images/_DateRangeFilled.svg';
import { styled } from '@mui/material/styles';

const HoverFalse = styled('div')(({ theme }) => ({
  backgroundColor: theme.palette['Primary']['Contrast'],
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 12px`,
  boxSizing: `border-box`,
  height: 'auto',
}));

const LeftSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const Frame2 = styled('div')({
  backgroundColor: `rgba(209, 228, 255, 1)`,
  borderRadius: `18px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `52px`,
  height: `52px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Icon1 = styled(SvgIcon)(({ theme }) => ({
  color: theme.palette['Primary']['Main'],
  width: `34px`,
  height: `34px`,
  margin: `0px`,
}));

const Text = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 12px`,
});

const Frame1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `227px`,
  margin: `0px`,
});

const MeetWithEllenCho = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `0.15000000596046448px`,
  textDecoration: `none`,
  lineHeight: `142.99999475479126%`,
  textTransform: `none`,
  flexGrow: `1`,
  margin: `0px`,
}));

const ZoomCall = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Secondary'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  width: `227px`,
  margin: `4px 0px 0px 0px`,
}));

const RightSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 12px`,
});

const Link1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Link2 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(107, 104, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

function EventListItem(props) {
  return (
    <HoverFalse>
      <LeftSide>
        <Frame2>
          <Icon1 fontSize={'small'} component={DateRangeFilled1} />
        </Frame2>
        <Text>
          <Frame1>
            <MeetWithEllenCho>{`Meet with Ellen Cho`}</MeetWithEllenCho>
          </Frame1>
          <ZoomCall>{`Zoom Call`}</ZoomCall>
        </Text>
      </LeftSide>
      <RightSide>
        <Link1>
          <Link2>{`View`}</Link2>
        </Link1>
      </RightSide>
    </HoverFalse>
  );
}

export default EventListItem;
