/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import SidebarIcon from 'src/components/SidebarIcon/SidebarIcon';

const Property1Default = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `40px`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 32px`,
  boxSizing: `border-box`,
});

const SidebarIconBlue = styled(SidebarIcon)(({ theme }) => ({
  margin: `0px`,
}));

const SidebarIconGray = styled(SidebarIcon)(({ theme }) => ({
  margin: `0px 0px 0px 13px`,
}));

const Text = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Secondary'],
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  flexGrow: `1`,
  margin: `0px 0px 0px 13px`,
}));

function SidebarRow1(props) {
  return (
    <Property1Default>
      <SidebarIconBlue />
      <SidebarIconGray />
      <Text>{`Dashboard`}</Text>
    </Property1Default>
  );
}

export default SidebarRow1;
