/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

const useWelcome = () => {
  let data = {};
  let d = window.matchMedia("(min-width: 1100px)");
  let t = window.matchMedia("(min-width: 600px) and (max-width: 1100px)");
  let m = window.matchMedia("(max-width: 600px)");
  if(d.matches){
    data.size = "desktop"
  }else if(t.matches){
    data.size = "tablet"
  }else if(m.matches){
    data.size = "mobile"
  }
  let fns = {};
  return { data, fns };
};

export default useWelcome;
