/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Navbar2 from 'src/components/Navbar2/Navbar2';
import { animated, useSpring, easings } from 'react-spring';

const ScreenDesktop = styled('div')({
  background: `linear-gradient(180deg, rgba(213, 15, 217, 1) -3.0616171314629196e-15%, rgba(213, 15, 217, 0) 99.99999999999999%)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100vw',
  height: '100vh',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Navbar21 = styled(Navbar2)(({ theme }) => ({
  width: `1440px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Frame2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  position: 'absolute',
  left: '50%',
  top: '29%',
  transform: 'translate(-50%, -50%)'
});

const Hrucoin = animated(
  styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Azeret Mono`,
    fontWeight: `400`,
    fontSize: `200px`,
    letterSpacing: `-6.4px`,
    textDecoration: `none`,
    lineHeight: `62px`,
    textTransform: `none`,
    textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
    margin: `0px`,
  })
);

const OneBlockAtATime = animated(
  styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Azeret Mono`,
    fontWeight: `400`,
    fontSize: `24px`,
    letterSpacing: `-1.2px`,
    textDecoration: `none`,
    lineHeight: `62px`,
    textTransform: `none`,
    position: 'absolute',
    left: '50%',
    top: '48%',
    transform: 'translate(-50%, -50%)'
  })
);

const Label = animated(
  styled('div')({
    background: `linear-gradient(90deg, rgba(123, 97, 255, 1) 27.623125519427568%, rgba(254, 136, 136, 1) 89.61456174389363%)`,
    borderRadius: `50px`,
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `20px`,
    boxSizing: `border-box`,
    position: 'absolute',
    left: '50%',
    top: '43%',
    transform: 'translate(-50%, -50%)'
  })
);

const Frame1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px 5px`,
  boxSizing: `border-box`,
  height: `24px`,
  margin: `0px`,
});

const Text = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `3px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Label1 = animated(
  styled('div')(({ theme }) => ({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    color: theme.palette['Primary']['Contrast'],
    fontStyle: `normal`,
    fontFamily: `Azeret Mono`,
    fontWeight: `700`,
    fontSize: `29px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    textTransform: `none`,
    margin: `0px`,
  }))
);

const HrucoinWasCreatedWit = animated(
  styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Azeret Mono`,
    fontWeight: `700`,
    fontSize: `36px`,
    letterSpacing: `-0.69px`,
    textDecoration: `none`,
    lineHeight: `92.00000166893005%`,
    textTransform: `none`,
    position: 'absolute',
    left: '41%',
    top: '68%',
    transform: 'translate(-50%, -50%)'
  })
);

function Welcome(props) {
  const [HrucoinSpring, HrucoinApi] = useSpring(() => ({
    config: {
      duration: 1500,
      easing: easings['easeOutExpo'],
    },
    delay: 0,
    from: { opacity: 0 },
  }));

  const [OneBlockAtATimeSpring, OneBlockAtATimeApi] = useSpring(() => ({
    config: {
      duration: 250,
      easing: easings['easeOutExpo'],
    },
    delay: 0,
    from: { opacity: 0 },
  }));

  const [LabelSpring, LabelApi] = useSpring(() => ({
    config: {
      duration: 3000,
      easing: easings['easeOutExpo'],
    },
    delay: 0,
    from: { opacity: 0 },
  }));

  const [Label1Spring, Label1Api] = useSpring(() => ({
    config: {
      duration: 3000,
      easing: easings['easeOutExpo'],
    },
    delay: 0,
    from: { opacity: 0 },
  }));

  const [HrucoinWasCreatedWitSpring, HrucoinWasCreatedWitApi] = useSpring(
    () => ({
      config: {
        duration: 4000,
        easing: easings['easeOutExpo'],
      },
      delay: 0,
      from: { opacity: 0 },
    })
  );

  React.useEffect(() => {
    HrucoinApi.start({
      ...{ opacity: 1 },
      delay: 0,
      config: { duration: 1500 },
    });
    LabelApi.start({ ...{ opacity: 1 }, delay: 0, config: { duration: 3000 } });
    OneBlockAtATimeApi.start({
      ...{ opacity: 1 },
      delay: 0,
      config: { duration: 250 },
    });
    Label1Api.start({
      ...{ opacity: 1 },
      delay: 0,
      config: { duration: 3000 },
    });
    HrucoinWasCreatedWitApi.start({
      ...{ opacity: 1 },
      delay: 0,
      config: { duration: 4000 },
    });
  }, []);

  return (
    <ScreenDesktop>
      <Navbar21 />
      <Frame2>
        <Hrucoin style={{ ...HrucoinSpring }}>{`HRUCOIN`}</Hrucoin>
      </Frame2>
      <OneBlockAtATime style={{ ...OneBlockAtATimeSpring }}>
        {`One block at a time`}
      </OneBlockAtATime>
      <Label style={{ ...LabelSpring }}>
        <Frame1>
          <Text>
            <Label1 style={{ ...Label1Spring }}>
              {`Innovating Defi Health.`}
            </Label1>
          </Text>
        </Frame1>
      </Label>
      <HrucoinWasCreatedWit style={{ ...HrucoinWasCreatedWitSpring }}>
        {`HRUCOIN Was Created With 3 Core Values...

To Improve Mental Health in the Crypto Space

To Allow Blockchain Adaptions And onboarding for Mental Health Establishments

To improve Crypto in preparation for its mainstream adoption
`}
      </HrucoinWasCreatedWit>
    </ScreenDesktop>
  );
}

export default Welcome;
