/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Navbar2 from 'src/components/Navbar2/Navbar2';
import useWelcome from 'src/components/Welcome/useWelcome';

const ScreenDesktop = styled('div', {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ data }) => ({
  backgroundColor: `rgba(0, 0, 0, 0.2)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: data.size === 'mobile' ? `834px` : `731px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
}));

const Navbar21 = styled(Navbar2, {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ theme, data }) => ({
  width: data.size === 'mobile' ? `396px` : `1440px`,
  height: data.size === 'mobile' ? 'unset' : `60px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Hrucoin = styled('div', {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ data }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nova Round`,
  fontWeight: `400`,
  fontSize: data.size === 'mobile' ? `40px` : `96px`,
  letterSpacing: data.size === 'mobile' ? `-2px` : `-4.8px`,
  textDecoration: `none`,
  lineHeight: `62px`,
  textTransform: `none`,
  position: `absolute`,
  left: data.size === 'mobile' ? `116px` : `523px`,
  top: data.size === 'mobile' ? `219px` : `280px`,
}));

const InnovatingBlockchain = styled('div', {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ data }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nova Round`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `-1.6px`,
  textDecoration: `none`,
  lineHeight: `62px`,
  textTransform: `none`,
  position: `absolute`,
  left: data.size === 'mobile' ? `94px` : `462px`,
  top: data.size === 'mobile' ? `375px` : `439px`,
  width: data.size === 'mobile' ? `289px` : 'unset',
}));

const Button1 = styled('div', {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ data }) => ({
  backgroundColor: `rgba(123, 97, 255, 1)`,
  boxShadow: `0px 6px 7px rgba(123, 97, 255, 0.3)`,
  borderRadius: `8px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `14px 50px`,
  boxSizing: `border-box`,
  left: data.size === 'mobile' ? `100px` : `622px`,
  top: data.size === 'mobile' ? `313px` : `382px`,
}));

const LearnMore = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.96px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

function Welcome(props) {
  const { data } = useWelcome();

  return (
    <ScreenDesktop data={data}>
      <Navbar21 data={data} />
      <Hrucoin data={data}>{`HRUCOIN`}</Hrucoin>
      <InnovatingBlockchain data={data}>
        {`Innovating Blockchain Health Services`}
      </InnovatingBlockchain>
      <Button1 data={data}>
        <LearnMore>{`Learn More`}</LearnMore>
      </Button1>
    </ScreenDesktop>
  );
}

export default Welcome;
