/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Navbar2 from 'src/components/Navbar2/Navbar2';

const ScreenDesktop = styled('div')({
  backgroundColor: `rgba(191, 38, 158, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `887px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Navbar21 = styled(Navbar2)(({ theme }) => ({
  width: `1440px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Q1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nova Round`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `-1.6px`,
  textDecoration: `none`,
  lineHeight: `62px`,
  textTransform: `none`,
  position: `absolute`,
  left: `462px`,
  top: `140px`,
});

const Button1 = styled('div')({
  backgroundColor: `rgba(123, 97, 255, 1)`,
  boxShadow: `0px 6px 7px rgba(123, 97, 255, 0.3)`,
  borderRadius: `8px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `14px 50px`,
  boxSizing: `border-box`,
  left: `622px`,
  top: `282px`,
});

const LearnMore = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.96px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Hrucoin = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Nova Round`,
  fontWeight: `400`,
  fontSize: `96px`,
  letterSpacing: `-4.8px`,
  textDecoration: `none`,
  lineHeight: `62px`,
  textTransform: `none`,
  position: `absolute`,
  left: `467px`,
  top: `449px`,
});

function Welcome(props) {
  return (
    <ScreenDesktop>
      <Navbar21 />
      <Q1>{`Innovating Blockchain Health Services`}</Q1>
      <Button1>
        <LearnMore>{`Learn More`}</LearnMore>
      </Button1>
      <Hrucoin>{`HRUCOIN`}</Hrucoin>
    </ScreenDesktop>
  );
}

export default Welcome;
