/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import Quest22Image from 'src/assets/images/Team_Quest2_2.png';
import { styled } from '@mui/material/styles';
import Navbar2 from 'src/components/Navbar2/Navbar2';
import Card8 from 'src/components/Card8/Card8';

const Team1 = styled('div')({
  backgroundColor: `rgba(208, 36, 191, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `731px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const WwwQuestAi = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(85, 85, 85, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
  position: `absolute`,
  left: `61px`,
  top: `1963px`,
}));

const FigmaToReactUpgradeY = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(85, 85, 85, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `61px`,
  top: `1907px`,
}));

const Quest22 = styled('img')({
  height: `46.47px`,
  width: `189.22px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `59px`,
  top: `1839px`,
});

const HruTeam = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `80px`,
  letterSpacing: `-2.4px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `513px`,
  position: `absolute`,
  left: `520px`,
  top: `69px`,
});

const WhoAreWe = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `45px`,
  letterSpacing: `-1.35px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `323px`,
  height: `44px`,
  position: `absolute`,
  left: `539px`,
  top: `143px`,
});

const Price = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `34px`,
  letterSpacing: `-1px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `22px`,
  top: `14px`,
});

const Navbar21 = styled(Navbar2)(({ theme }) => ({
  width: `1440px`,
  height: `57px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Hrucoin = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `-0.66px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `513px`,
  position: `absolute`,
  left: `134px`,
  top: `19px`,
});

const Card81 = styled(Card8)(({ theme }) => ({
  width: `329px`,
  height: `440px`,
  position: `absolute`,
  left: `44px`,
  top: `246px`,
}));

const Card82 = styled(Card8)(({ theme }) => ({
  width: `329px`,
  height: `440px`,
  position: `absolute`,
  left: `1068px`,
  top: `246px`,
}));

const Card83 = styled(Card8)(({ theme }) => ({
  width: `329px`,
  height: `440px`,
  position: `absolute`,
  left: `536px`,
  top: `246px`,
}));

function Team(props) {
  return (
    <Team1>
      <Helmet>
        <title>Team</title>
      </Helmet>
      <WwwQuestAi>{`www.quest.ai`}</WwwQuestAi>
      <FigmaToReactUpgradeY>
        {`Figma to React. Upgrade your workflow.`}
      </FigmaToReactUpgradeY>
      <Quest22 src={Quest22Image} loading="lazy" alt={'Quest2 2'} />
      <HruTeam>{`HRUTeam`}</HruTeam>
      <WhoAreWe>{`Who are We?`}</WhoAreWe>
      <Price>{`Defi Crisis Management `}</Price>
      <Navbar21 />
      <Hrucoin>{`HRUCOIN`}</Hrucoin>
      <Card81 />
      <Card82 />
      <Card83 />
    </Team1>
  );
}

export default Team;
