/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import { styled } from '@mui/material/styles';
import Navbar2 from 'src/components/Navbar2/Navbar2';

const Desktop11 = styled('div')({
  backgroundColor: `rgba(249, 17, 17, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Navbar21 = styled(Navbar2)(({ theme }) => ({
  width: `1441px`,
  height: `60px`,
  position: `absolute`,
  left: `-1px`,
  top: `0px`,
}));

function Desktop1(props) {
  return (
    <Desktop11>
      <Helmet>
        <title>Desktop - 1</title>
      </Helmet>
      <Navbar21 />
    </Desktop11>
  );
}

export default Desktop1;
