/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Image1Image from 'src/assets/images/Navbar2_image_1.png';
import HamburgerImage from 'src/assets/images/Navbar2_Hamburger.png';
import { styled } from '@mui/material/styles';

const ScreenDesktopTypeQue = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px 80px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const Items = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const Frame1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Image1 = styled('img')({
  height: `40px`,
  width: `43px`,
  objectFit: `cover`,
  margin: `0px`,
});

const MenuStructure = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `36px`,
});

const Items1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const AboutUs = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Background']['Paper'],
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

const OurTeam = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Background']['Paper'],
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  opacity: `0.6000000238418579`,
  margin: `0px 0px 0px 40px`,
}));

const Learn = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Background']['Paper'],
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  opacity: `0.6000000238418579`,
  margin: `0px 0px 0px 40px`,
}));

const Social = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Background']['Paper'],
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  opacity: `0.6000000238418579`,
  margin: `0px 0px 0px 40px`,
}));

const Community = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Background']['Paper'],
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  opacity: `0.6000000238418579`,
  margin: `0px 0px 0px 40px`,
}));

const Presale = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Background']['Paper'],
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 40px`,
}));

const Hamburger = styled('img')({
  height: `15px`,
  width: `21px`,
  margin: `0px 0px 0px 40px`,
});

function Navbar2(props) {
  return (
    <ScreenDesktopTypeQue>
      <Items>
        <Frame1>
          <Image1 src={Image1Image} loading="lazy" alt={'image 1'} />
        </Frame1>
        <MenuStructure>
          <Items1>
            <AboutUs>{`about us`}</AboutUs>
            <OurTeam>{`our team`}</OurTeam>
            <Learn>{`learn`}</Learn>
            <Social>{`social`}</Social>
            <Community>{`community`}</Community>
            <Presale>{`presale`}</Presale>
          </Items1>
          {false && (
            <Hamburger src={HamburgerImage} loading="lazy" alt={'Hamburger'} />
          )}
        </MenuStructure>
      </Items>
    </ScreenDesktopTypeQue>
  );
}

export default Navbar2;
