/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Logo1Image from 'src/assets/images/MoonBase_Logo1.png';
import Logo2Image from 'src/assets/images/MoonBase_Logo2.png';
import Logo3Image from 'src/assets/images/MoonBase_Logo3.png';
import Logo4Image from 'src/assets/images/MoonBase_Logo4.png';
import { styled } from '@mui/material/styles';
import MoonBase1Image from 'src/assets/images/MoonBase_Moon_Base.png';
import HeroSpacemanImage from 'src/assets/images/MoonBase_Hero_spaceman.png';
import Sec2ImageImage from 'src/assets/images/MoonBase_Sec_2_Image.png';
import MoonbaseNav from 'src/components/MoonbaseNav/MoonbaseNav';

const MoonBase1 = styled('div')({
  backgroundImage: `url(${MoonBase1Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const MoonbaseNav1 = styled(MoonbaseNav)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Hero = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `790px`,
  margin: `0px`,
});

const HeroLeftSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 0px 145px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const TakeYourNextProjectT = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `500`,
  fontSize: `100px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `94px`,
  textTransform: `none`,
  width: `621.55px`,
  margin: `0px`,
});

const WeReAnAgencyWithOurH = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `300`,
  fontSize: `26px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `538.18px`,
  margin: `54px 0px 0px 0px`,
});

const Logos = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `4px 0px`,
  boxSizing: `border-box`,
  margin: `54px 0px 0px 0px`,
});

const Logo1 = styled('img')({
  height: `23.66px`,
  width: `114.7px`,
  margin: `0px`,
});

const Logo2 = styled('img')({
  height: `31.54px`,
  width: `60.93px`,
  margin: `0px 0px 0px 47px`,
});

const Logo3 = styled('img')({
  height: `25px`,
  width: `100px`,
  margin: `0px 0px 0px 47px`,
});

const Logo4 = styled('img')({
  height: `17.92px`,
  width: `101.08px`,
  margin: `0px 0px 0px 47px`,
});

const HeroSpaceman = styled('div')({
  backgroundImage: `url(${HeroSpacemanImage})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `flex-start`,
  flexGrow: `1`,
  height: `1232px`,
  margin: `0px 0px 0px -523px`,
});

const Sec2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `80px 140px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `930px`,
  margin: `0px`,
});

const Sec2Image = styled('div')({
  backgroundImage: `url(${Sec2ImageImage})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `640px`,
  margin: `0px`,
});

const About = styled('div')({
  backgroundColor: `rgba(235, 247, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `42px 60px`,
  boxSizing: `border-box`,
  width: `605px`,
  margin: `-276px 0px 0px 0px`,
});

const WeReMoonBase = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  margin: `0px`,
});

const LoremIpsumDolorSitAm = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `17px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `485px`,
  margin: `20px 0px 0px 0px`,
});

function MoonBase(props) {
  return (
    <MoonBase1>
      <MoonbaseNav1 />
      <Hero>
        <HeroLeftSide>
          <TakeYourNextProjectT>
            {`Take your next project to the moon`}
          </TakeYourNextProjectT>
          <WeReAnAgencyWithOurH>
            {`We’re an agency with our heads in the clouds. Let us create and push your next project into the stratosphere. `}
          </WeReAnAgencyWithOurH>
          <Logos>
            <Logo1 src={Logo1Image} loading="lazy" alt={'Logo1'} />
            <Logo2 src={Logo2Image} loading="lazy" alt={'Logo2'} />
            <Logo3 src={Logo3Image} loading="lazy" alt={'Logo3'} />
            <Logo4 src={Logo4Image} loading="lazy" alt={'Logo4'} />
          </Logos>
        </HeroLeftSide>
        <HeroSpaceman></HeroSpaceman>
      </Hero>
      <Sec2>
        <Sec2Image></Sec2Image>
        <About>
          <WeReMoonBase>{`We’re Moon Base`}</WeReMoonBase>
          <LoremIpsumDolorSitAm>
            {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam leo urna turpis semper sed a vulputate mi. Diam nisl non in et mattis. Sit pulvinar cursus integer lectus sagittis bibendum. Rhoncus cras diam tellus convallis.

Condimentum aliquam arcu arcu massa purus egestas ante vulputate nisl. Nisl tellus non, eu velit mauris, lectus vel, ornare. Pellentesque in at ac tortor ipsum commodo. Sit sed nulla blandit tincidunt velit aliquam dui ipsum amet. Tincidunt sit mauris, tempus tincidunt orci integer.`}
          </LoremIpsumDolorSitAm>
        </About>
      </Sec2>
    </MoonBase1>
  );
}

export default MoonBase;
