/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import SummitLogo1Image from 'src/assets/images/HeroAnimate1_summit_logo_1.png';
import SImage from 'src/assets/images/HeroAnimate1_S.png';
import UImage from 'src/assets/images/HeroAnimate1_U_1.png';
import MImage from 'src/assets/images/HeroAnimate1_M_2.png';
import M1Image from 'src/assets/images/HeroAnimate1_M_1.png';
import IImage from 'src/assets/images/HeroAnimate1_I_1.png';
import TImage from 'src/assets/images/HeroAnimate1_T_1.png';
import HamburgerImage from 'src/assets/images/HeroAnimate1_Hamburger.png';
import Ellipse1Image from 'src/assets/images/HeroAnimate1_Ellipse_1.png';
import MaskGroupImage from 'src/assets/images/HeroAnimate1_Mask_group.png';
import Ellipse2Image from 'src/assets/images/HeroAnimate1_Ellipse_2.png';
import HImage from 'src/assets/images/HeroAnimate1_H.png';
import RImage from 'src/assets/images/HeroAnimate1_R.png';
import U1Image from 'src/assets/images/HeroAnimate1_U.png';
import M2Image from 'src/assets/images/HeroAnimate1_M.png';
import I1Image from 'src/assets/images/HeroAnimate1_I.png';
import T1Image from 'src/assets/images/HeroAnimate1_T.png';
import { styled } from '@mui/material/styles';

const HeroAnimate11 = styled('div')({
  background: `linear-gradient(180deg, rgba(255, 243, 214, 1) -3.0616171314629196e-15%, rgba(255, 255, 255, 0) 99.99999999999999%)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `823px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Desktop1 = styled('div')({
  backgroundColor: `rgba(211, 1, 1, 0.2)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 0px 40px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
});

const Navbar2 = styled('div')(({ theme }) => ({
  backgroundColor: theme.palette['Background']['Paper'],
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px 80px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `60px`,
  margin: `0px`,
}));

const Items = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
});

const Frame1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const AnimateFont = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const Icon1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const SummitLogo1 = styled('img')({
  height: `23px`,
  width: `23px`,
  objectFit: `cover`,
  margin: `0px`,
});

const S = styled('img')({
  height: `21.59px`,
  width: `15.78px`,
  margin: `0px 0px 0px 2.9581563472747803px`,
});

const U = styled('img')({
  height: `21.37px`,
  width: `19.2px`,
  margin: `0px 0px 0px 2.9581563472747803px`,
});

const M = styled('img')({
  height: `21.09px`,
  width: `26.81px`,
  margin: `0px 0px 0px 2.9581563472747803px`,
});

const M1 = styled('img')({
  height: `21.09px`,
  width: `26.81px`,
  margin: `0px 0px 0px 2.9581563472747803px`,
});

const I = styled('img')({
  height: `21.09px`,
  width: `6.03px`,
  margin: `0px 0px 0px 2.9581563472747803px`,
});

const T = styled('img')({
  height: `21.09px`,
  width: `14.6px`,
  margin: `0px 0px 0px 2.9581563472747803px`,
});

const MenuStructure = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `36px`,
});

const Items1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const AboutUs = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `1.2px`,
  textDecoration: `none`,
  textTransform: `uppercase`,
  margin: `0px`,
}));

const OurTeam = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `1.2px`,
  textDecoration: `none`,
  textTransform: `uppercase`,
  opacity: `0.6000000238418579`,
  margin: `0px 0px 0px 40px`,
}));

const Learn = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `1.2px`,
  textDecoration: `none`,
  textTransform: `uppercase`,
  opacity: `0.6000000238418579`,
  margin: `0px 0px 0px 40px`,
}));

const Hamburger = styled('img')({
  height: `15px`,
  width: `21px`,
  margin: `0px 0px 0px 40px`,
});

const SignUp = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const LogIn = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `1.2px`,
  textDecoration: `none`,
  textTransform: `uppercase`,
  opacity: `0.6000000238418579`,
  margin: `0px`,
}));

const ButtonContained = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  boxShadow: theme.customShadows['Elevation']['2'].boxShadow,
  borderRadius: `24px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px 7px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 40px`,
  overflow: `hidden`,
}));

const UnstyledButton = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `4px 10px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const Button1 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `13px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `22px`,
  textTransform: `uppercase`,
  margin: `0px`,
}));

const Content = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `21px 0px 0px 0px`,
});

const Logo = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const SummitLogo = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `86px`,
  width: `86px`,
  margin: `0px`,
});

const Ellipse1 = styled('img')({
  height: `86px`,
  width: `86px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const MaskGroup = styled('img')({
  height: `86px`,
  width: `86px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Ellipse2 = styled('img')({
  height: `86px`,
  width: `86px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const AnimateFont1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `41px 0px 0px 0px`,
  overflow: `hidden`,
});

const H = styled('img')({
  height: `145.95px`,
  width: `106.68px`,
  margin: `0px`,
});

const R = styled('img')({
  height: `144.51px`,
  width: `129.78px`,
  margin: `0px 0px 0px 20px`,
});

const U1 = styled('img')({
  height: `142.59px`,
  width: `181.23px`,
  margin: `0px 0px 0px 20px`,
});

const M2 = styled('img')({
  height: `142.59px`,
  width: `181.23px`,
  margin: `0px 0px 0px 20px`,
});

const I1 = styled('img')({
  height: `142.59px`,
  width: `40.74px`,
  margin: `0px 0px 0px 20px`,
});

const T1 = styled('img')({
  height: `142.59px`,
  width: `98.7px`,
  margin: `0px 0px 0px 20px`,
});

const LoremIpsumDolarTextN = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `15px`,
  letterSpacing: `1px`,
  textDecoration: `none`,
  lineHeight: `22px`,
  textTransform: `uppercase`,
  width: `355px`,
  margin: `40px 0px 0px 0px`,
});

const Btns = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `40px 0px 0px 0px`,
});

const ButtonContained1 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  boxShadow: theme.customShadows['Elevation']['2'].boxShadow,
  borderRadius: `234px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `180px`,
  height: `60px`,
  margin: `0px`,
  overflow: `hidden`,
}));

const UnstyledButton1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `8px 22px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const Button2 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Info']['Contrast'],
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `15px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  margin: `0px`,
}));

const ButtonOutlined = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.2)`,
  border: `3px solid rgba(0, 0, 0, 0.5)`,
  boxSizing: `border-box`,
  borderRadius: `234px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  width: `180px`,
  height: `60px`,
  margin: `0px 0px 0px 28px`,
  overflow: `hidden`,
});

const UnstyledButton2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `8px 22px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const Button3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `15px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  margin: `0px`,
});

function HeroAnimate1(props) {
  return (
    <HeroAnimate11>
      <Desktop1>
        <Navbar2>
          <Items>
            <Frame1>
              <AnimateFont>
                <Icon1>
                  <SummitLogo1
                    src={SummitLogo1Image}
                    loading="lazy"
                    alt={'summit logo 1'}
                  />
                </Icon1>
                <S src={SImage} loading="lazy" alt={'S'} />
                <U src={UImage} loading="lazy" alt={'U'} />
                <M src={MImage} loading="lazy" alt={'M'} />
                <M1 src={M1Image} loading="lazy" alt={'M'} />
                <I src={IImage} loading="lazy" alt={'I'} />
                <T src={TImage} loading="lazy" alt={'T'} />
              </AnimateFont>
            </Frame1>
            <MenuStructure>
              <Items1>
                <AboutUs>{`about us`}</AboutUs>
                <OurTeam>{`our team`}</OurTeam>
                <Learn>{`learn`}</Learn>
              </Items1>
              <Hamburger
                src={HamburgerImage}
                loading="lazy"
                alt={'Hamburger'}
              />
            </MenuStructure>
            <SignUp>
              <LogIn>{`LOG-in`}</LogIn>
              <ButtonContained>
                <UnstyledButton>
                  <Button1>{`SIGN-UP`}</Button1>
                </UnstyledButton>
              </ButtonContained>
            </SignUp>
          </Items>
        </Navbar2>
        <Content>
          <Logo>
            <SummitLogo>
              <Ellipse1 src={Ellipse1Image} loading="lazy" alt={'Ellipse 1'} />
              <MaskGroup
                src={MaskGroupImage}
                loading="lazy"
                alt={'Mask group'}
              />
              <Ellipse2 src={Ellipse2Image} loading="lazy" alt={'Ellipse 2'} />
            </SummitLogo>
            <AnimateFont1>
              <H src={HImage} loading="lazy" alt={'H'} />
              <R src={RImage} loading="lazy" alt={'R'} />
              <U1 src={U1Image} loading="lazy" alt={'U'} />
              <M2 src={M2Image} loading="lazy" alt={'M'} />
              <I1 src={I1Image} loading="lazy" alt={'I'} />
              <T1 src={T1Image} loading="lazy" alt={'T'} />
            </AnimateFont1>
          </Logo>
          <LoremIpsumDolarTextN>
            {`Improving blockchain mentalHealth`}
          </LoremIpsumDolarTextN>
          <Btns>
            <ButtonContained1>
              <UnstyledButton1>
                <Button2>{`About Us`}</Button2>
              </UnstyledButton1>
            </ButtonContained1>
            <ButtonOutlined>
              <UnstyledButton2>
                <Button3>{`Presale`}</Button3>
              </UnstyledButton2>
            </ButtonOutlined>
          </Btns>
        </Content>
      </Desktop1>
    </HeroAnimate11>
  );
}

export default HeroAnimate1;
