/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Avatar } from '@mui/material';
import Avatar1Image from 'src/assets/images/Card8_Avatar.png';
import PinImage from 'src/assets/images/Card8_Pin.png';
import InstagramCircleIconPImage from 'src/assets/images/Card8_instagram_circle_icon_png_24.png';
import TwitterIconCircleBlaImage from 'src/assets/images/Card8_twitter_icon_circle_black_logo_35827D553B_seeklogo.png';
import { styled } from '@mui/material/styles';

const TypeQuest = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: theme.customShadows['Elevation']['6'].boxShadow,
  borderRadius: `8px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `529px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
}));

const Content = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `40px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const About = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Avatar1 = styled(Avatar)({
  width: `130px`,
  height: `130px`,
  margin: `0px`,
});

const Details = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 10px`,
  boxSizing: `border-box`,
  width: `339px`,
  margin: `30px 0px 0px 0px`,
});

const NameAndTitle = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Name = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

const Title = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Secondary'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

const Details1 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
}));

const Location = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
});

const Pin = styled('img')({
  height: `15.83px`,
  width: `11.67px`,
  margin: `0px`,
});

const Location1 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `uppercase`,
  margin: `0px 0px 0px 10px`,
}));

const Social = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 97px`,
  boxSizing: `border-box`,
  margin: `20px 0px 0px 0px`,
  overflow: `hidden`,
});

const InstagramCircleIconP = styled('img')({
  height: `30px`,
  width: `40px`,
  objectFit: `cover`,
  margin: `0px`,
});

const TwitterIconCircleBla = styled('img')({
  height: `30px`,
  width: `30px`,
  objectFit: `cover`,
  margin: `0px 0px 0px 10px`,
});

function Card8(props) {
  return (
    <TypeQuest>
      <Content>
        <About>
          <Avatar1 variant="circular" src={Avatar1Image} alt={'Avatar'} />
        </About>
        <Details>
          <NameAndTitle>
            <Name>{`Ellen Cho`}</Name>
            <Title>{`UX Designer`}</Title>
          </NameAndTitle>
          <Details1>
            {`Lorem ipsum test to be seen and not read for placement only. Lorem ipsum test to be seen.`}
          </Details1>
          <Location>
            <Pin src={PinImage} loading="lazy" alt={'Pin'} />
            <Location1>{`San Francisco, CA`}</Location1>
          </Location>
          <Social>
            <InstagramCircleIconP
              src={InstagramCircleIconPImage}
              loading="lazy"
              alt={'instagram-circle-icon-png-24'}
            />
            <TwitterIconCircleBla
              src={TwitterIconCircleBlaImage}
              loading="lazy"
              alt={'twitter-icon-circle-black-logo-35827D553B-seeklogo'}
            />
          </Social>
        </Details>
      </Content>
    </TypeQuest>
  );
}

export default Card8;
