/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import PaginationItem from 'src/components/PaginationItem/PaginationItem';

const TypeQuest = styled('div')(({ theme }) => ({
  boxShadow: theme.customShadows['Elevation']['1'].boxShadow,
  borderRadius: `8px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  width: '100%',
}));

const PaginationItem1 = styled(PaginationItem)(({ theme }) => ({
  width: `44px`,
  height: `44px`,
  margin: `0px`,
}));

const Divider = styled('div')({
  backgroundColor: `rgba(228, 228, 228, 1)`,
  width: `1px`,
  height: `44px`,
  margin: `0px`,
});

const PaginationItem2 = styled(PaginationItem)(({ theme }) => ({
  width: `44px`,
  height: `44px`,
  margin: `0px`,
}));

function Pagination2(props) {
  return (
    <TypeQuest>
      <PaginationItem1 />
      <Divider></Divider>
      <PaginationItem2 />
    </TypeQuest>
  );
}

export default Pagination2;
