/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ArrowRImage from 'src/assets/images/PaginationItem_Arrow_R.png';
import ArrowLImage from 'src/assets/images/PaginationItem_Arrow_L.png';
import { styled } from '@mui/material/styles';

const TypeNumberHoverFalse = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `44px`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px`,
  boxSizing: `border-box`,
});

const Q1 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Ellipsis = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `0px 0px 0px 10px`,
}));

const ArrowR = styled('img')({
  height: `12px`,
  width: `6px`,
  margin: `0px 0px 0px 10px`,
});

const ArrowL = styled('img')({
  height: `12px`,
  width: `6px`,
  margin: `0px 0px 0px 10px`,
});

function PaginationItem(props) {
  return (
    <TypeNumberHoverFalse>
      <Q1>{`1`}</Q1>
      <Ellipsis>{`...`}</Ellipsis>
      <ArrowR src={ArrowRImage} loading="lazy" alt={'Arrow R'} />
      <ArrowL src={ArrowLImage} loading="lazy" alt={'Arrow L'} />
    </TypeNumberHoverFalse>
  );
}

export default PaginationItem;
