/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import HeroAnimate1 from 'src/components/HeroAnimate1/HeroAnimate1';

const HeroAnimate12 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: '100%',
});

const HeroAnimate13 = styled(HeroAnimate1)(({ theme }) => ({
  height: `823px`,
  width: `1255px`,
  margin: `0px`,
}));

function HeroAnimate11(props) {
  return (
    <HeroAnimate12>
      <HeroAnimate13 />
    </HeroAnimate12>
  );
}

export default HeroAnimate11;
