/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import Quest22Image from 'src/assets/images/Goals_Quest2_2.png';
import { styled } from '@mui/material/styles';
import Card18 from 'src/components/Card18/Card18';
import Navbar2 from 'src/components/Navbar2/Navbar2';

const Goals1 = styled('div')({
  backgroundColor: `rgba(208, 36, 191, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Card181 = styled(Card18)(({ theme }) => ({
  width: `390px`,
  position: `absolute`,
  left: `1038px`,
  top: `360px`,
}));

const Card182 = styled(Card18)(({ theme }) => ({
  width: `390px`,
  position: `absolute`,
  left: `516px`,
  top: `360px`,
}));

const WwwQuestAi = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(85, 85, 85, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
  position: `absolute`,
  left: `61px`,
  top: `1963px`,
}));

const FigmaToReactUpgradeY = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(85, 85, 85, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `61px`,
  top: `1907px`,
}));

const Quest22 = styled('img')({
  height: `46.47px`,
  width: `189.22px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `59px`,
  top: `1839px`,
});

const HruGoals = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `80px`,
  letterSpacing: `-2.4px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `513px`,
  position: `absolute`,
  left: `495px`,
  top: `126px`,
});

const WhatDoWePlanToChange = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `45px`,
  letterSpacing: `-1.35px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `819px`,
  height: `62px`,
  position: `absolute`,
  left: `352px`,
  top: `208px`,
});

const InTheFollowingPagesY = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `665px`,
  height: `246px`,
  left: `607px`,
  top: `390px`,
});

const Price = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `-1px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `-72px`,
  top: `59px`,
});

const Price1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `-1px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `1058px`,
  top: `454px`,
});

const Price2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `34px`,
  letterSpacing: `-1px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `22px`,
  top: `14px`,
});

const Label = styled('div')({
  background: `linear-gradient(90deg, rgba(123, 97, 255, 1) 27.623125519423546%, rgba(254, 136, 136, 1) 89.6145617438896%)`,
  borderRadius: `50px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `20px`,
  boxSizing: `border-box`,
  width: `457px`,
  height: `48px`,
  left: `454px`,
  top: `270px`,
});

const Frame1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px 5px`,
  boxSizing: `border-box`,
  height: `24px`,
  margin: `0px`,
});

const Text = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `3px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Label1 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `29px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

const Navbar21 = styled(Navbar2)(({ theme }) => ({
  width: `1440px`,
  height: `57px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Hrucoin = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `-0.66px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `none`,
  width: `513px`,
  position: `absolute`,
  left: `134px`,
  top: `19px`,
});

const Card183 = styled(Card18)(({ theme }) => ({
  width: `390px`,
  position: `absolute`,
  left: `14px`,
  top: `360px`,
}));

const Price3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `-1px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `34px`,
  top: `449px`,
});

function Goals(props) {
  return (
    <Goals1>
      <Helmet>
        <title>Goals</title>
      </Helmet>
      <Card181 />
      <Card182 />
      <WwwQuestAi>{`www.quest.ai`}</WwwQuestAi>
      <FigmaToReactUpgradeY>
        {`Figma to React. Upgrade your workflow.`}
      </FigmaToReactUpgradeY>
      <Quest22 src={Quest22Image} loading="lazy" alt={'Quest2 2'} />
      <HruGoals>{`HRUGoals`}</HruGoals>
      <WhatDoWePlanToChange>
        {`What do we plan to change...`}
      </WhatDoWePlanToChange>
      <InTheFollowingPagesY>
        <Price>{`Helping Providers Integrate Blockchains`}</Price>
      </InTheFollowingPagesY>
      <Price1>{`Helping Users Stay calm.`}</Price1>
      <Price2>{`Defi Crisis Management `}</Price2>
      <Label>
        <Frame1>
          <Text>
            <Label1>{`Let’s say... A LOT`}</Label1>
          </Text>
        </Frame1>
      </Label>
      <Navbar21 />
      <Hrucoin>{`HRUCOIN`}</Hrucoin>
      <Card183 />
      <Price3>{`Helping Traders and Defi in General`}</Price3>
    </Goals1>
  );
}

export default Goals;
