/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import { styled } from '@mui/material/styles';
import Navbar2 from 'src/components/Navbar2/Navbar2';

const Rectangle11 = styled('div')({
  backgroundColor: `rgba(143, 97, 97, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `1080px`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: '100%',
});

const Navbar21 = styled(Navbar2)(({ theme }) => ({
  height: `60px`,
  width: `1441px`,
  margin: `0px`,
}));

const Hrucoin = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `80px`,
  letterSpacing: `-2.4px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `uppercase`,
  margin: `212px 0px 0px 0px`,
});

const InnovatingDefiMental = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Azeret Mono`,
  fontWeight: `700`,
  fontSize: `64px`,
  letterSpacing: `-1.92px`,
  textDecoration: `none`,
  lineHeight: `92.00000166893005%`,
  textTransform: `uppercase`,
  margin: `212px 0px 0px 0px`,
});

function Rectangle1(props) {
  return (
    <Rectangle11>
      <Helmet>
        <title>Rectangle 1</title>
      </Helmet>
      <Navbar21 />
      <Hrucoin>{`HRUCOIN`}</Hrucoin>
      <InnovatingDefiMental>
        {`Innovating Defi Mental Care`}
      </InnovatingDefiMental>
    </Rectangle11>
  );
}

export default Rectangle1;
